/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zhongjing_dcyy_com_app_SerialPort */

#ifndef _Included_zhongjing_dcyy_com_app_SerialPort
#define _Included_zhongjing_dcyy_com_app_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zhongjing_dcyy_com_app_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_zhongjing_dcyy_com_app_SerialPort_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     zhongjing_dcyy_com_app_SerialPort
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zhongjing_dcyy_com_app_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
